[package]
name = "FINAL_PROJECT"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.215", features = ["derive"] }
plotters = {version = "0.3.7", default-features = false, features = ["evcxr", "all_series"]}
ndarray = "0.16.1"
linfa = "0.7.0"